spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/crm_system?currentSchema=public
    username: postgres
    password: lhs22LI=D=
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
    database: postgresql

secret_key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
server:
  port: 8080